### ISSUE TITLE
Error in w7

### ISSUE THREAD

**Issue by ghost** [L3cr0f/DccwBypassUAC#1]
Can't find the ordinal 40 in Cabinet.dll ! 

Windows 7 Professional SP1 6.1.7601

**Comment by L3cr0f** [comment]
At this moment, the exploit does not support Windows 7 machines because I use some functions that were included in the API in Windows 8 (those related with the extraction of the DLL). In the [requirements](https://github.com/L3cr0f/DccwBypassUAC#2-requirements) section I mention the currently vulnerable machines. However, the vulnerability also appears in Windows 7 machines, so if the exploit was redesigned so as to use only supported functions by this OS, it would work.

Thanks to try it! :)
