### ISSUE TITLE
autoElevateProcess- Bug ! ^^

### ISSUE THREAD

**Issue by ghost** [L3cr0f/DccwBypassUAC#3]
Hey, how to do about this ? !  is it a bug ?!

**Comment by L3cr0f** [comment]
Well, in my opinion "autoElevate" processes could be useful in some cases, but only if they were developed in a secure way, something Microsoft seemed to forget in many cases.

**Comment by SynapseRans** [comment]
I dont wana make another ticket so ill ask here

why doesnt this version work on win 7,

also what can i use to base64 encode the dll file and split it?

**Comment by L3cr0f** [comment]
This exploit doesn't work om Windows 7 systems because to encode the payload I use a function of "Cabinet.dll" that is not included in this OS. So, when you execute it in such systems, they throw an error, since they cannot find the mentioned function.
Regarding the DLL encoding-compressing process, it is not uploaded. However, you could try to create your own encoding-compressing function by using the inverse functions of the decoding-decompressing funtion of the exploit.
I hope I've been able to help you :)
